=== LasagniAndrea/Data/Bobcat/Source/SpheresServices/SpheresIO/IOCompare/CompareParameters.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Configuration">
<!--
 The root configuration must have 2 child nodes : Templates et Parameters.
 The Templates node is a collection of Template, IOW comparison models.
 The Parameters node is the collection of the configuration datas for all the possible IO parameters that they are editable by the user.
 
 -->
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="1" name="Templates">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="Template">
                <!--     
    All the Parameter nodes are owned by one single reconciliation model :
    - they have type EXCEPT.
    - they must fetch a unique Spheres table (in other words they must share the same table name)
    -->
              <!--
    All the EXCEPT parameters must be string type
    --> 
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Id" type="xs:string" />
                    <xs:element name="Parameters">
                      <xs:complexType mixed="true">
                        <xs:sequence minOccurs="0">
                          <xs:element maxOccurs="unbounded" name="Parameter">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element minOccurs="1" maxOccurs="1" name="Id" type="xs:string" />
                                <xs:element minOccurs="1" maxOccurs="1" name="Type" type="xs:string" />
                                <xs:element maxOccurs="1" name="SQLInfos">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element minOccurs="0" maxOccurs="unbounded" name="SQLInfo">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element minOccurs="1" maxOccurs="1" name="SQLTable" type="xs:string" />
                                            <xs:element minOccurs="1" maxOccurs="1" name="SQLField" type="xs:string" />
                                            <xs:element minOccurs="1" maxOccurs="1" name="SQLType" type="xs:string" />
                                            <xs:element minOccurs="0" maxOccurs="1" name="SQLOperator" type="xs:string" />
                                            <xs:element minOccurs="1" maxOccurs="1" name="XPath" type="xs:string" />
                                            <xs:element minOccurs="1" maxOccurs="1" name="XPathType" type="xs:string" />
                                            <xs:element minOccurs="0" maxOccurs="1" name="GroupByRule" type="xs:string" />
                                          </xs:sequence>
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="1" maxOccurs="1" name="Parameters">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="Parameter">
                <!-- All the FILTER type parameters will be concatenated to the sql where condition using the order they are listed -->
                <!-- The sql type is compliant with the IOTaskParamsParam.datatype values set -->
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="1" maxOccurs="1" name="Id" type="xs:string" />
                    <xs:element minOccurs="1" maxOccurs="1" name="Type" type="xs:string" />
                    <xs:element minOccurs="1" maxOccurs="1" name="SQLInfos">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="0" maxOccurs="unbounded" name="SQLInfo">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element minOccurs="1" maxOccurs="1" name="SQLTable" type="xs:string" />
                                <xs:element minOccurs="1" maxOccurs="1" name="SQLField" type="xs:string" />
                                <xs:element minOccurs="1" maxOccurs="1" name="SQLType" type="xs:string" />
                                <xs:element minOccurs="0" maxOccurs="1" name="SQLOperator" type="xs:string" />
                                <xs:element minOccurs="1" maxOccurs="1" name="XPath" type="xs:string" />
                                <xs:element minOccurs="1" maxOccurs="1" name="XPathType" type="xs:string" />
                                <xs:element minOccurs="0" maxOccurs="1" name="GroupByRule" type="xs:string" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="defaultValue" type="xs:string" use="optional" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== LasagniAndrea/Data/SpheresIO/IOCompare/CompareParameters.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
  RD 20131129 [19272] Compare clearer data
  - Add parameter CLEARERLIST
  - Parametr DTBUSINESS: on table TRADE use DTBUSINESS column instead of DTTRADE column
  RD 20131210 [19313] 
  - Add parameter IDPROCESS_L
  RD 20210304 
  - Use TRADEXML.TRADEXML instead of TRADE.TRADEXML
 -->
<Configuration 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="CompareParameters.xsd">
  <Templates>
    <Template>
      <Id>SumOfQuantities</Id>
      <Parameters>
        <Parameter>
          <Id>LASTQTY</Id>
          <Type>EXCEPT</Type>
          <SQLInfos>
            <SQLInfo>
              <SQLTable>dbo.EXTLDATADET</SQLTable>
              <SQLField>DATAXML</SQLField>
              <SQLType>integer</SQLType>
              <XPath>fixml:TrdCaptRpt/@LastQty</XPath>
              <XPathType></XPathType>
              <GroupByRule>SelectSum</GroupByRule>
            </SQLInfo>
            <SQLInfo>
              <SQLTable>dbo.VUE_ARCH_NEGO</SQLTable>
              <SQLField>QUANT_OP</SQLField>
              <SQLType>integer</SQLType>
              <XPath></XPath>
              <XPathType></XPathType>
              <GroupByRule>SelectSum</GroupByRule>
            </SQLInfo>
            <SQLInfo>
              <SQLTable>dbo.VUE_ARCH_POS_OUV</SQLTable>
              <SQLField>QUANT_OP</SQLField>
              <SQLType>integer</SQLType>
              <XPath></XPath>
              <XPathType></XPathType>
              <GroupByRule>SelectSum</GroupByRule>
            </SQLInfo>
            <SQLInfo>
              <SQLTable>dbo.TRADEXML</SQLTable>
              <SQLField>TRADEXML</SQLField>
              <SQLType>integer</SQLType>
              <XPath>efs:EfsML/trade/efs:exchangeTradedDerivative/fixml:FIXML/fixml:TrdCaptRpt/@LastQty</XPath>
              <XPathType></XPathType>
              <GroupByRule>SelectSum</GroupByRule>
            </SQLInfo>
            <SQLInfo>
              <!-- TODO MF 20120124 the quantity can be filtered just on the initial trade quantity -->
              <SQLTable>dbo.VW_TRADE_POSETD</SQLTable>
              <SQLField>QTY</SQLField>
              <SQLType>integer</SQLType>
              <XPath></XPath>
              <XPathType></XPathType>
              <GroupByRule>SelectSum</GroupByRule>
            </SQLInfo>
          </SQLInfos>
        </Parameter>
        <Parameter>
          <Id>"LONG"</Id>
          <Type>EXCEPT</Type>
          <SQLInfos>
            <SQLInfo>
              <SQLTable>dbo.EXTLDATADET</SQLTable>
              <SQLField>DATAXML</SQLField>
              <SQLType>integer</SQLType>
              <XPath>fixml:PosRpt/fixml:Qty/@Long</XPath>
              <XPathType></XPathType>
              <GroupByRule>SelectSum</GroupByRule>
            </SQLInfo>
            <SQLInfo>
              <SQLTable>dbo.VUE_ARCH_POS_OUV</SQLTable>
              <SQLField>QUANT_OP</SQLField>
              <SQLType>integer</SQLType>
              <XPath></XPath>
              <XPathType></XPathType>
              <GroupByRule>SelectSum</GroupByRule>
            </SQLInfo>
            <SQLInfo>
              <!-- TODO MF 20120124 the quantity can be filtered just on the initial trade quantity 
              (warning: same control on long/short quantities) -->
              <SQLTable>dbo.VW_TRADE_POSETD</SQLTable>
              <SQLField>QTY</SQLField>
              <SQLType>integer</SQLType>
              <XPath></XPath>
              <XPathType></XPathType>
              <GroupByRule>SelectSum</GroupByRule>
            </SQLInfo>
          </SQLInfos>
        </Parameter>
        <Parameter>
          <Id>"SHORT"</Id>
          <Type>EXCEPT</Type>
          <SQLInfos>
            <SQLInfo>
              <SQLTable>dbo.EXTLDATADET</SQLTable>
              <SQLField>DATAXML</SQLField>
              <SQLType>integer</SQLType>
              <XPath>fixml:PosRpt/fixml:Qty/@Short</XPath>
              <XPathType></XPathType>
              <GroupByRule>SelectSum</GroupByRule>
            </SQLInfo>
            <SQLInfo>
              <SQLTable>dbo.VUE_ARCH_POS_OUV</SQLTable>
              <SQLField>QUANT_OP</SQLField>
              <SQLType>integer</SQLType>
              <XPath></XPath>
              <XPathType></XPathType>
              <GroupByRule>SelectSum</GroupByRule>
            </SQLInfo>
            <SQLInfo>
              <!-- TODO MF 20120124 the quantity can be filtered just on the initial trade quantity 
              (warning: same control on long/short quantities) -->
              <SQLTable>dbo.VW_TRADE_POSETD</SQLTable>
              <SQLField>QTY</SQLField>
              <SQLType>integer</SQLType>
              <XPath></XPath>
              <XPathType></XPathType>
              <GroupByRule>SelectSum</GroupByRule>
            </SQLInfo>
          </SQLInfos>
        </Parameter>
        <Parameter>
          <Id>TAXCOMAMT</Id>
          <Type>EXCEPT</Type>
          <SQLInfos>
            <SQLInfo>
              <SQLTable>dbo.FLX_DEV</SQLTable>
              <SQLField>MONT_FRAIS</SQLField>
              <SQLType>integer</SQLType>
              <XPath></XPath>
              <XPathType></XPathType>
              <GroupByRule>SelectSum</GroupByRule>
            </SQLInfo>
            <SQLInfo>
              <SQLTable>dbo.EXTLDATADET</SQLTable>
              <SQLField>DATAXML</SQLField>
              <SQLType>integer</SQLType>
              <XPath>efs:AcctRpt/efs:Amts/efs:TaxComAmt/@amt</XPath>
              <XPathType></XPathType>
              <GroupByRule>SelectSum</GroupByRule>
            </SQLInfo>
            <SQLInfo>
              <SQLTable>dbo.EVENT</SQLTable>
              <SQLField>TAXCOMAMT</SQLField>
              <SQLType>integer</SQLType>
              <XPath></XPath>
              <XPathType></XPathType>
              <GroupByRule>SelectSum</GroupByRule>
            </SQLInfo>
          </SQLInfos>
        </Parameter>
        <Parameter>
          <Id>TAXCOMCCY</Id>
          <Type>EXCEPT</Type>
          <SQLInfos>
            <SQLInfo>
              <SQLTable>dbo.EXTLDATADET</SQLTable>
              <SQLField>DATAXML</SQLField>
              <SQLType>string</SQLType>
              <XPath>efs:AcctRpt/efs:Amts/efs:TaxComAmt/@ccy</XPath>
              <XPathType></XPathType>
              <GroupByRule>GroupBy</GroupByRule>
            </SQLInfo>
            <SQLInfo>
              <SQLTable>dbo.FLX_DEV</SQLTable>
              <SQLField>CD_DEV</SQLField>
              <SQLType>string</SQLType>
              <XPath></XPath>
              <XPathType></XPathType>
              <GroupByRule>GroupBy</GroupByRule>
            </SQLInfo>
            <SQLInfo>
              <SQLTable>dbo.EVENT</SQLTable>
              <SQLField>TAXCOMCCY</SQLField>
              <SQLType>string</SQLType>
              <XPath></XPath>
              <XPathType></XPathType>
              <GroupByRule>GroupBy</GroupByRule>
            </SQLInfo>
          </SQLInfos>
        </Parameter>
        <Parameter>
          <Id>TAXCOMACT</Id>
          <Type>EXCEPT</Type>
          <SQLInfos>
            <SQLInfo>
              <SQLTable>dbo.EXTLDATADET</SQLTable>
              <SQLField>DATAXML</SQLField>
              <SQLType>string</SQLType>
              <XPath>efs:AcctRpt/efs:Amts/efs:TaxComAmt/@act</XPath>
              <XPathType></XPathType>
              <GroupByRule>SelectMin</GroupByRule>
            </SQLInfo>
            <SQLInfo>
              <SQLTable>dbo.EVENT</SQLTable>
              <SQLField>TAXCOMACT</SQLField>
              <SQLType>integer</SQLType>
              <XPath></XPath>
              <XPathType></XPathType>
              <GroupByRule>SelectMin</GroupByRule>
            </SQLInfo>
          </SQLInfos>
        </Parameter>
        <Parameter>
        <Id>COLLAMT</Id>
        <Type>EXCEPT</Type>
        <SQLInfos>
          <SQLInfo>
            <SQLTable>dbo.EXTLDATADET</SQLTable>
            <SQLField>DATAXML</SQLField>
            <SQLType>string</SQLType>
            <XPath>efs:AcctRpt/efs:Amts/efs:CollAmt/@amt</XPath>
            <XPathType></XPathType>
            <GroupByRule>SelectSum</GroupByRule>
          </SQLInfo>
          <SQLInfo>
            <SQLTable>dbo.FLX_DEV</SQLTable>
            <SQLField>MONT_DEPOSIT</SQLField>
            <SQLType>integer</SQLType>
            <XPath></XPath>
            <XPathType></XPathType>
            <GroupByRule>SelectSum</GroupByRule>
          </SQLInfo>
          <SQLInfo>
            <SQLTable>dbo.EVENT</SQLTable>
            <SQLField>COLLAMT</SQLField>
            <SQLType>integer</SQLType>
            <XPath></XPath>
            <XPathType></XPathType>
            <GroupByRule>SelectSum</GroupByRule>
          </SQLInfo>
        </SQLInfos>
        </Parameter>
        <Parameter>
          <Id>COLLCCY</Id>
          <Type>EXCEPT</Type>
          <SQLInfos>
            <SQLInfo>
              <SQLTable>dbo.EXTLDATADET</SQLTable>
              <SQLField>DATAXML</SQLField>
              <SQLType>string</SQLType>
              <XPath>efs:AcctRpt/efs:Amts/efs:CollAmt/@ccy</XPath>
              <XPathType></XPathType>
              <GroupByRule>GroupBy</GroupByRule>
            </SQLInfo>
            <SQLInfo>
              <SQLTable>dbo.FLX_DEV</SQLTable>
              <SQLField>CD_DEV</SQLField>
              <SQLType>string</SQLType>
              <XPath></XPath>
              <XPathType></XPathType>
              <GroupByRule>GroupBy</GroupByRule>
            </SQLInfo>
            <SQLInfo>
              <SQLTable>dbo.EVENT</SQLTable>
              <SQLField>COLLCCY</SQLField>
              <SQLType>string</SQLType>
              <XPath></XPath>
              <XPathType></XPathType>
              <GroupByRule>GroupBy</GroupByRule>
            </SQLInfo>
          </SQLInfos>
        </Parameter>
        <Parameter>
          <Id>COLLACT</Id>
          <Type>EXCEPT</Type>
          <SQLInfos>
            <SQLInfo>
